In [1]:
import numpy as np
from sympy import *

## 과제 1.

In [2]:
A = np.array([[2, 4, -2, 1], [-2, -5, 7, 3], [3, 7, -8, 6]])
print(A)

[[ 2  4 -2  1]
 [-2 -5  7  3]
 [ 3  7 -8  6]]


(1) 열공간이 Rk의 부분 공간일 때 k 를 구하시오

In [5]:
c1 = Matrix(A.T).rref()
print(c1)

(Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1],
[0, 0, 0]]), (0, 1, 2))


In [6]:
c2 = Matrix(A).rank()
print(c2)

3


In [8]:
# 따라서 k 는 3

(2) 영공간이 Rk의 부분 공간일 때 k를 구하시오

In [11]:
print(Matrix(A).rref())

(Matrix([
[1, 0,  9, 0],
[0, 1, -5, 0],
[0, 0,  0, 1]]), (0, 1, 3))


x3 = s  라 할 때,
 
 x1 = -9s, x2 = 5s, x4 = 0 이다. 이때 선형결합으로 나타내면
 
 x = [[-9], [5], [1], [0]]*s 이다.
 
 이때 k 는 4이다.

확인을 해보면

In [12]:
print(Matrix(A).nullspace())

[Matrix([
[-9],
[ 5],
[ 1],
[ 0]])]


인 것을 알 수 있다.

(3) 열공간과 영공간의 영텍버가 아닌 벡터를 구하시오

벡터는 각각

열공간에서 3차원이므로 (1, 0, 0) 이다

영공간에서 s = 1 일 때도 되므로 (-9, 5, 1, 0) 이다.

(4) (3, -1, 3) 이 영공간, 열공간에 속하는 지 밝히시오

In [13]:
# 영공간, 열공간에 속하는 지 알기 위해서는 Ax = b 식을 이용한다

In [47]:
b = np.array([3, -1, 3])
aug = np.column_stack((A, b))
Matrix(aug).rref()

(Matrix([
 [1, 0,  9, 0,      5],
 [0, 1, -5, 0, -30/17],
 [0, 0,  0, 1,   1/17]]), (0, 1, 3))

In [48]:
Matrix(aug).rank()

3

인 것을 보아 열공간의 차원이 바뀌지 않았으므로 (3, -1, 3) 은 열공간에 속한다

(5) (3, -2, -2, 0) 이 영공간, 열공간에 속하는 지 밝히시오

In [68]:
b = np.array([3, -2, -2, 0])
Aug = np.column_stack((A.T, b)).T
Matrix(Aug).rref()

(Matrix([
 [1, 0, 0, 0],
 [0, 1, 0, 0],
 [0, 0, 1, 0],
 [0, 0, 0, 1]]), (0, 1, 2, 3))

In [69]:
Matrix(Aug).rank()

4

A의 영공간과 Aug 의 영공간의 차원이 같으므로 (3, -2, -2, 0) 은 영공간에 속한다

In [76]:
print(np.dot(A, b))

[  2 -10  11]


(3, -2, -2, 0) 는 차원이 다르므로 열공간에 속하지 않고,

둘이 곱했을 때 0 이 안나왔으므로 영공간에 속하지 않는다.

영공간 : Ax = 0 을 만족하는 것
열공간 : Ax = b 를 만족하는 것

(6) 열공간과 행공간의 기저를 구하시오

In [78]:
Matrix(A.T).rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1],
 [0, 0, 0]]), (0, 1, 2))

In [77]:
Matrix(A).rref()

(Matrix([
 [1, 0,  9, 0],
 [0, 1, -5, 0],
 [0, 0,  0, 1]]), (0, 1, 3))

열공간에서 3차원이므로 기저는 표준단위벡터 (1, 0, 0) ... 이다

행공간에서 기저는 (1, 0, 9, 0), (0, 1, -5, 0), (0, 0, 0, 1) 이다

(7) Rank, nullity 를 구하시오

In [79]:
Matrix(A).rank()

3

nullity(A) = n(미지수) - rank(A) 이므로
nulluty = 4 - 3 = 1 이다.

## 과제 2.

(1) 다음과 같은 heading 을 갖는 표를 만들고 아래 행렬들에 대하여 구하여라

| 행렬번호 | 열의 수 | 영공간의 기저 | Nullity | 열공간의 기저 | Rank |
|----------|---------|---------------|---------|---------------|-----|
|a|3|(8/5, -4/5, 1)|1|(1, 0),(0, 1)|2|
|b|5|(-6, -4, 1, 0, 0)|3|(1, 0, 1)|2|
|||(2, 2, 0, 1, 0)||(0, 1, 1)||
|||(-6, -5, 0, 0, 1)||||
|c|6|(3/5, 1/5, -1/5, 1, 0, 0)|3|(1, 0, 0, 1)|3|
|||(2/5, 4/5, 1/5, 0, 1, 0)||(0, 1, 0, 0)||
|||(1/10, 7/10, -1/5, 0, 0, 1)||(0, 0, 1, 1)||
|d|4|(3, 5, 1, 0)|2|(1, 1, 0, 2)|2|
|||(1, 1, 0, 1)||(0, 1, 1, 0)||

In [27]:
a = np.array([[1, 2, 0], [-1, 3, 4]])
b = np.array([[1, -1, 2, 0, 1], [-1, 2, 2, -2, 4], [0, 1, 4, -2, 5]])
c = np.array([[1, -1, 2, 0, 0, 1], [-1, 1, 3, 1, -1, 0], [1, 1, -1, -1, -1, -1], [2, 0, 1, -1, -1, 0]])
d = np.array([[1, -1, 2, 0], [-2, 1, 1, 1], [-1, 0, 3, 1], [2, -2, 4, 0]])

### 1번째 행렬 a

In [13]:
print(Matrix(a).rref())
print(Matrix(a).rank())

(Matrix([
[1, 0, -8/5],
[0, 1,  4/5]]), (0, 1))
2


x1 = 8/5

x2 = -4/5

In [17]:
print(Matrix(a.T).rref())

(Matrix([
[1, 0],
[0, 1],
[0, 0]]), (0, 1))


### 2번째 행렬 b

In [14]:
print(Matrix(b).rref())
print(Matrix(b).rank())

(Matrix([
[1, 0, 6, -2, 6],
[0, 1, 4, -2, 5],
[0, 0, 0,  0, 0]]), (0, 1))
2


x3 = s, x4 = t, x5 = u

x1 = -6s + 2t -6u

x2 = -4s + 2t -5u

s = 1, t = 0, u = 0
> x1 = -6, x2 = -4, x3 = 1, x4 = 0, x5 = 0

s = 0, t = 1, u = 0
> x1 = 2, x2 = 2, x3 = 0, x4 = 1, x5 = 0

s = 0, t = 0, u = 1
> x1 = -6, x2 = -5, x3 = 0, x4 = 0, x5 = 1

In [18]:
print(Matrix(b.T).rref())

(Matrix([
[1, 0, 1],
[0, 1, 1],
[0, 0, 0],
[0, 0, 0],
[0, 0, 0]]), (0, 1))


### 3번째 행렬 c

In [15]:
print(Matrix(c).rref())
print(Matrix(c).rank())

(Matrix([
[1, 0, 0, -3/5, -2/5, -1/10],
[0, 1, 0, -1/5, -4/5, -7/10],
[0, 0, 1,  1/5, -1/5,   1/5],
[0, 0, 0,    0,    0,     0]]), (0, 1, 2))
3


x4 = s, x5 = t, x6 = u

x1 = 3/5s + 2/5t + 1/10u

x2 = 1/5s + 4/5t + 7/10u

x3 = -1/5s + 1/5t - 1/5u

s = 1, t = 0, u = 0
> x1 = 3/5, x2 = 1/5, x3 = -1/5, x4 = 1, x5 = 0, x6 = 0

s = 0, t = 1, u = 0
> x1 = 2/5, x2 = 4/5, x3 = 1/5, x4 = 0, x5 = 1, x6 = 0

s = 0, t = 0, u = 1
> x1 = 1/10, x2 = 7/10, x3 = -1/5, x4 = 0, x5 = 0, x6 = 1

In [25]:
print(Matrix(c.T).rref())

(Matrix([
[1, 0, 0, 1],
[0, 1, 0, 0],
[0, 0, 1, 1],
[0, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0]]), (0, 1, 2))


### 4번째 행렬 d

In [16]:
print(Matrix(d).rref())
print(Matrix(d).rank())

(Matrix([
[1, 0, -3, -1],
[0, 1, -5, -1],
[0, 0,  0,  0],
[0, 0,  0,  0]]), (0, 1))
2


x3 = s, x4 = t

x1 = 3s + t
x2 = 5s + t

s = 1, t = 0
> x1 = 3, x2 = 5, x3 = 1, x4 = 0

s = 0, t = 1
> x1 = 1, x2 = 1, x3 = 0, x4 = 1

In [26]:
print(Matrix(d.T).rref())

(Matrix([
[1, 0, 1, 2],
[0, 1, 1, 0],
[0, 0, 0, 0],
[0, 0, 0, 0]]), (0, 1))


(2) 위에서 만든 표를 보고, column의 수와 nullity, rank의 관계를 구하시오

> column 의 수와 nullity, rank 는 nullity = column - rank 의 관계가 있다.