In [2]:
import numpy as np

## 1. 다음 행렬의 크기를 Numpy를 이용하여 구하라

In [90]:
A=np.array([3, 6, 0, 7])

In [91]:
A.shape

(4,)

In [92]:
A=np.array([[7, 13, 2], [0, 6, 4]])

In [93]:
A.shape

(2, 3)

In [94]:
A=np.array([[4, 1, -2], [-4, 9, 12], [2, 15, -6]])

In [95]:
A.shape

(3, 3)

## 2. 2x2, 3x3 크기의 identity matrix 를 Numpy를 이용하여 구하라

In [96]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [97]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 3. 다음 matrix에 대하여 각 질문의 답을 Numpy를 이용하여 구하라

In [98]:
A=np.array([[7, 5, 0, -8],[2, 3, -2 ,9],[ 9, -5, -6, 3]])

In [99]:
#a24     3th low     4th column
A[1,3],   A[2, :],     A[:, 3]

(9, array([ 9, -5, -6,  3]), array([-8,  9,  3]))

## 4. 다음 두 행렬에 대하여 Numpy를 이용해서 값을 확인하여라

In [100]:
A=np.array([[4, 7, 1], [8, 5, 3], [3, 2, 4]])

In [101]:
B=np.array([[5, -3, 7], [4, 5, -4], [3, 0, 1]])

In [102]:
2*A-np.eye(1)

array([[ 7., 13.,  1.],
       [15.,  9.,  5.],
       [ 5.,  3.,  7.]])

In [103]:
3*A-2*B

array([[  2,  27, -11],
       [ 16,   5,  17],
       [  3,   6,  10]])

## 5. 다음 행렬 A, B에 대하여 Numpy를 이용해서 값을 확인하여라

In [104]:
A=np.array([[1, 3, 2], [4, 5, 7]])

In [105]:
B=np.array([[5, -3], [0, 2], [4, 7]])

In [106]:
np.dot(A,B)

array([[13, 17],
       [48, 47]])

In [107]:
np.dot(B,A)

array([[ -7,   0, -11],
       [  8,  10,  14],
       [ 32,  47,  57]])

## 6. 다음 행렬 A의 임의의 자연수 n에 대하여 A^n을 구하여라 (Numpy 이용 가능)

In [3]:
C=np.array([[0, 0, 1, 0], [0, 0, 0, 1], [-1 ,0 ,0, 0], [0, -1, 0, 0]])

In [5]:
C2=np.dot(C, C)

In [6]:
C2

array([[-1,  0,  0,  0],
       [ 0, -1,  0,  0],
       [ 0,  0, -1,  0],
       [ 0,  0,  0, -1]])

In [7]:
C3=np.dot(C2, C)

In [9]:
C3

array([[ 0,  0, -1,  0],
       [ 0,  0,  0, -1],
       [ 1,  0,  0,  0],
       [ 0,  1,  0,  0]])

In [10]:
C4=np.dot(C3, C)

In [12]:
C4

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [13]:
C5=np.dot(C4,C)

In [14]:
C5

array([[ 0,  0,  1,  0],
       [ 0,  0,  0,  1],
       [-1,  0,  0,  0],
       [ 0, -1,  0,  0]])

In [15]:
# 이를 보아 C의 n 승은 허수 i 와 똑같이 4번째마다 첫번째 C의 모습과 같아지는 것을 볼 수 있다.

## 7. 다음 행렬 A, B에 대하여 값을 확인하여라

In [112]:
A=np.array([[1, 2], [3, 4]])

In [113]:
B=np.array([[4, 3], [2, 1]])

In [114]:
print(np.dot(A,B).T)

[[ 8 20]
 [ 5 13]]


In [115]:
print(np.dot(A.T,B.T))

[[13  5]
 [20  8]]


In [116]:
print(np.dot(B.T,A.T))

[[ 8 20]
 [ 5 13]]


## 8. 다음 행렬 A, B에 대하여 값을 확인하여라

In [117]:
A=np.array([[1, 2], [3, 4]])

In [118]:
B=np.array([[5, 6], [7, 8]])

In [119]:
np.trace(np.dot(A,B))

69

In [120]:
np.trace(np.dot(B,A))

69