In [29]:
import numpy as np

## 1. numpy 를 사용하여 행렬식을 구하여라

In [30]:
A=np.array([[2, 4, 3], [0, 1, -1], [3, 5, 7]])

In [31]:
A

array([[ 2,  4,  3],
       [ 0,  1, -1],
       [ 3,  5,  7]])

In [32]:
np.linalg.det(A)

2.999999999999999

## 2. 다음 행렬의 행렬식, 수반행렬, 역행렬 등을 구해라

In [66]:
A=np.array([[1, 2, 0], [0, 4, 7], [5, 0, 3]])

In [67]:
np.linalg.det(A)

81.99999999999994

In [68]:
np.linalg.inv(A)
#A의 역행렬 = adj(A)/det(A)

array([[ 0.14634146, -0.07317073,  0.17073171],
       [ 0.42682927,  0.03658537, -0.08536585],
       [-0.24390244,  0.12195122,  0.04878049]])

## 3-c. elementary row operation matrix 들의 행렬식을 구해보고, 교재의 정리를 이용하여 row operation에 대하여 다음이 성립함을 보여라

In [35]:
ro1=np.array([[0, 1, 0], [1, 0, 0], [0, 0, 1]])
ro2=np.array([[1, 0, 0], [0, 1, 0], [0, 0, 5]])
ro3=np.array([[1, 0, 0], [0, 1, 0], [-4, 0, 1]])

In [36]:
print(np.linalg.det(ro1))
print(np.linalg.det(ro2))
print(np.linalg.det(ro3))

-1.0
4.999999999999999
1.0


**det(EA) = det(E) det(A) 를 증명하는 방법**

$교재에있는 정리 1.8과 1.9에 의하여$
> E 에 대하여 det(EA) = det(E) det(A) 임을 3가지 elementary operation 를 사용하여 정의한다.

In [37]:
A=np.array([[0, 1, 2], [4, 2, 0], [-6, 0, -4]]) #라고 했을 때

In [38]:
np.linalg.det(np.dot(ro1, A))

-40.0

In [39]:
np.linalg.det(np.dot(ro2, A))

199.99999999999991

In [40]:
np.linalg.det(np.dot(ro3, A))

40.0

가 나오는 것을 알 수 있는데 이때 det(ro1, 2, 3)은 각각 determinant가 -1 4 1 이 나오는 것을 알 수 있다. 그렇다면 det(EA)=det(E)det(A)가 맞기 위해서는 det(A)가 40이 나와야 하므로

In [41]:
np.linalg.det(A)

40.0

이 나오게 된다. 따라서 row operation에 대하여 그 어떤 행렬과 곱하더라도 **det(EA)= det(E)det(A)** 가 성립한다.

## 3-d. 다음 matrix A에 대하여 그 밑의 elementary row operation들을 차례로 적용하면서 operation 종류와 결과에 대하여 관찰한 내용을 써라.

In [70]:
A=np.array([[0, 1, 2], [1, 0, 3], [4, -3, 8]])

In [71]:
E1=np.array([[0, 1, 0], [1, 0, 0], [0, 0, 1]])

In [72]:
E2=np.array([[1, 0, 0], [0, 1, 0], [-4, 0, 1]])

In [73]:
E3=np.array([[1, 0, 0], [0, 1, 0], [0, 3, 1]])

In [74]:
E4=np.array([[1, 0, 0], [0, 1, 0], [0, 0, 0.5]])

In [75]:
E5=np.array([[1, 0, 0], [0, 1, -2], [0, 0, 1]])

In [76]:
E6=np.array([[1, 0, -3], [0, 1, 0], [0, 0, 1]])

## 3-e. elementary row operation의 연속 적용으로 matrix A 를 만들어라.

In [77]:
A1 = np.dot(E1, A)
print(A1)

[[ 1  0  3]
 [ 0  1  2]
 [ 4 -3  8]]


In [78]:
A2 = np.dot(E2, A1)
print(A2)

[[ 1  0  3]
 [ 0  1  2]
 [ 0 -3 -4]]


In [79]:
A3 = np.dot(E3, A2)
print(A3)

[[1 0 3]
 [0 1 2]
 [0 0 2]]


In [80]:
A4 = np.dot(E4, A3)
print(A4)

[[1. 0. 3.]
 [0. 1. 2.]
 [0. 0. 1.]]


In [81]:
A5 = np.dot(E5, A4)
print(A5)

[[1. 0. 3.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [62]:
A6 = np.dot(E6, A5)
print(A6)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


이를 보아 elementary row operation 이 연속 적용된 matrix A6은 Identity matrix가 된 것을 알 수 있다.
이때 사용된 elementary row operation은 순서대로
Interchange -> Replacement -> Replacement -> Scaling -> Replacement -> Replacement 이다.

## 3-f. det(EA) = det(E)det(A) 증명

>- 1. 연속적인 elementary operation 으로 인해 만들어 지는 A = (E_1)(E_2)...(E_p)I 의 성질을 이용해야한다. 
>- 2. A 가 가역행렬인 경우 A = E_1 E_2 ... E_s 로 나타낼 수 있다. det(AB) = det(E_1) det(E_2 ...E_s B) 일 때 이 방법을 계속 사용하면 det(E_1) det(E_2) ... det(E_s)det(B) 가 된다. 이때 det(B)만 따로 떼어내면 det(E_1 E_2 ... E_s )det(B) = det(A) det(B) 가 된다.
>- 3. A 가 가역행렬이 아닌 경우 AB 가 가역행렬이면 A 와 B 도 가역행렬임을 이용 A 가 가역행렬이 아니므로 AB 도 가역행렬이 아니다. 따라서 det(A) = 0, det(AB) = 0 이고 det(AB) = det(A) det(B) 이다. 여기서 또 A 가 가역일 필요충분조건은 det(A) 가 0 이 아님을 사용한다.