In [24]:
import numpy as np

## 1. for loop 이용하여 해 구하기

In [35]:
A=np.array([[1, -3, -2, 4], [1, 2, 4, -2], [2, 6, 7, -6], [4, -5, 2, 5]])
B=np.array([[2],[5],[6],[5]])
aug = np.column_stack((A, B))
print(aug)

[[ 1 -3 -2  4  2]
 [ 1  2  4 -2  5]
 [ 2  6  7 -6  6]
 [ 4 -5  2  5  5]]


In [36]:
aug[1, :]-=aug[0, :]
aug

array([[ 1, -3, -2,  4,  2],
       [ 0,  5,  6, -6,  3],
       [ 2,  6,  7, -6,  6],
       [ 4, -5,  2,  5,  5]])

In [37]:
aug[2, :]-=2*aug[0,:]
aug

array([[  1,  -3,  -2,   4,   2],
       [  0,   5,   6,  -6,   3],
       [  0,  12,  11, -14,   2],
       [  4,  -5,   2,   5,   5]])

In [38]:
aug[3, :]-=4*aug[0, :]
aug

array([[  1,  -3,  -2,   4,   2],
       [  0,   5,   6,  -6,   3],
       [  0,  12,  11, -14,   2],
       [  0,   7,  10, -11,  -3]])

In [39]:
aug[1, :] = aug[1, :]/5
aug[2, :] -= aug[1, :]*12
aug

array([[  1,  -3,  -2,   4,   2],
       [  0,   1,   1,  -1,   0],
       [  0,   0,  -1,  -2,   2],
       [  0,   7,  10, -11,  -3]])

In [40]:
aug[2, :]*=(-1)
aug

array([[  1,  -3,  -2,   4,   2],
       [  0,   1,   1,  -1,   0],
       [  0,   0,   1,   2,  -2],
       [  0,   7,  10, -11,  -3]])

In [41]:
aug[3, :]-=7*aug[1,:]
aug

array([[ 1, -3, -2,  4,  2],
       [ 0,  1,  1, -1,  0],
       [ 0,  0,  1,  2, -2],
       [ 0,  0,  3, -4, -3]])

In [42]:
aug[3, :]-=3*aug[2, :]
aug

array([[  1,  -3,  -2,   4,   2],
       [  0,   1,   1,  -1,   0],
       [  0,   0,   1,   2,  -2],
       [  0,   0,   0, -10,   3]])

In [43]:
r, c=np.shape(aug)
a=np.copy(aug[:, 0:c-1])
b=np.copy(aug[:, -1])
print(a, b)

[[  1  -3  -2   4]
 [  0   1   1  -1]
 [  0   0   1   2]
 [  0   0   0 -10]] [ 2  0 -2  3]


In [44]:
n=c-1
x=np.zeros((n, 1))
for i in range(n-1, -1, -1):
    x[i]=(b[i]-np.dot(a[i, :], x))/a[i,i]
print(x)

[[ 3.7]
 [ 1.1]
 [-1.4]
 [-0.3]]


## 2. sympy 와 rref 함수를 이용하여 구한 기약행사다리꼴과 비교

In [45]:
C=np.array([[1, 1, 2], [-1, -2, 3], [3, -7, 4]])
D=np.array([[8], [1], [10]])
Aug = np.column_stack((C, D))

In [46]:
from sympy import *

In [47]:
Matrix(Aug).rref()

(Matrix([
 [1, 0, 0, 3],
 [0, 1, 0, 1],
 [0, 0, 1, 2]]), (0, 1, 2))

* 손으로 푼 것과 x1, x2, x3 의 해가 같다