In [1]:
import numpy as np

## 1. 연립방정식의 첨가행렬과 상삼각행렬의 과정, 후치법을 이용한 해를 보이시오.
> ***손으로 직접 하는 것 포함***

 - 1번째 행렬

In [2]:
A=np.array([[5., -3, 5], [3, 4, 2], [4, 6, -7]])
b=np.array([[1], [5], [10]])
Aug = np.column_stack((A, b))
print(Aug)

[[ 5. -3.  5.  1.]
 [ 3.  4.  2.  5.]
 [ 4.  6. -7. 10.]]


In [3]:
Aug[1, :]=Aug[1, :]-Aug[0, :]*3/5
print(Aug)

[[ 5.  -3.   5.   1. ]
 [ 0.   5.8 -1.   4.4]
 [ 4.   6.  -7.  10. ]]


In [4]:
Aug[2, :]=Aug[2, :]-Aug[0, :]*4/5
print(Aug)

[[  5.   -3.    5.    1. ]
 [  0.    5.8  -1.    4.4]
 [  0.    8.4 -11.    9.2]]


In [5]:
Aug[2, :]=Aug[2, :]-Aug[1, :]*8/5
print(Aug)

[[ 5.   -3.    5.    1.  ]
 [ 0.    5.8  -1.    4.4 ]
 [ 0.   -0.88 -9.4   2.16]]


## **후치법** 이용

In [6]:
x3=Aug[2,3]/Aug[2,2]
x2=(x3+Aug[1,3])/Aug[1,1]
x1=(x2*3+x3*(-5)+Aug[0, 3])/Aug[0,0]
print(np.array([[x1], [x2], [x3]]))

[[ 0.86118855]
 [ 0.7190022 ]
 [-0.22978723]]


## **for loop** 이용

In [7]:
r,c=np.shape(Aug)
A=np.copy(Aug[:,0:c-1])
b=np.copy(Aug[:,-1])
print(A,b)

[[ 5.   -3.    5.  ]
 [ 0.    5.8  -1.  ]
 [ 0.   -0.88 -9.4 ]] [1.   4.4  2.16]


In [8]:
n=c-1
x=np.zeros((n, 1))
for i in range(n-1, -1, -1):
    x[i] = (b[i]-np.dot(A[i, :], x)) /A[i,i]
print(x)

[[ 0.86118855]
 [ 0.7190022 ]
 [-0.22978723]]


 - 2번째 행렬

In [9]:
a=np.array([[1, 2, 3], [3, -1, 2], [2, -2, 1]])
B=np.array([[11], [12], [2]])
aug = np.column_stack((a, B))
print(aug)

[[ 1  2  3 11]
 [ 3 -1  2 12]
 [ 2 -2  1  2]]


In [10]:
aug[1, :]-=aug[0, :]*3
print(aug)

[[  1   2   3  11]
 [  0  -7  -7 -21]
 [  2  -2   1   2]]


In [11]:
aug[2, :]-=aug[0, :]*2
print(aug)

[[  1   2   3  11]
 [  0  -7  -7 -21]
 [  0  -6  -5 -20]]


In [12]:
aug[1, :]=aug[1, :]/(-7)
print(aug)

[[  1   2   3  11]
 [  0   1   1   3]
 [  0  -6  -5 -20]]


In [13]:
aug[2, :]+=aug[1, :]*6
print(aug)

[[ 1  2  3 11]
 [ 0  1  1  3]
 [ 0  0  1 -2]]


## **후치법** 이용

In [14]:
x3=aug[2,3]
x2=aug[1,3]-x3
x1=aug[0,3]-2*x2-3*x3
print(np.array([[x1], [x2], [x3]]))

[[ 7]
 [ 5]
 [-2]]


## **for loop** 이용

In [18]:
r,c=np.shape(aug)
a=np.copy(aug[:, 0:c-1])
B=np.copy(aug[:,-1])
print(a,B)

[[1 2 3]
 [0 1 1]
 [0 0 1]] [11  3 -2]


In [19]:
n=c-1
X=np.zeros((n, 1))
for i in range(n-1, -1, -1):
    X[i] = (B[i]-np.dot(a[i, :], X)) /a[i,i]
print(X)

[[ 7.]
 [ 5.]
 [-2.]]


## 연립방정식의 첨가 행렬을 행사다리꼴로 바꿔라
> 해도 구하기

In [130]:
D=np.array([[1., 2, -1, -2], [-4, -8, 5, 6], [2, 4, -3, -2], [3, 6, -1, -10]])
F=np.array([[2], [-6], [3], [9]])
aa = np.column_stack((D, F))
print(aa)

[[  1.   2.  -1.  -2.   2.]
 [ -4.  -8.   5.   6.  -6.]
 [  2.   4.  -3.  -2.   3.]
 [  3.   6.  -1. -10.   9.]]


In [131]:
temp=np.copy(aa[2, :])
aa[2, :]=aa[1, :]
aa[1, :]=temp
print(aa)

[[  1.   2.  -1.  -2.   2.]
 [  2.   4.  -3.  -2.   3.]
 [ -4.  -8.   5.   6.  -6.]
 [  3.   6.  -1. -10.   9.]]


In [132]:
aa[1, :]-=aa[0, :]*2
print(aa)

[[  1.   2.  -1.  -2.   2.]
 [  0.   0.  -1.   2.  -1.]
 [ -4.  -8.   5.   6.  -6.]
 [  3.   6.  -1. -10.   9.]]


In [133]:
aa[2, :]+=aa[0, :]*4
print(aa)

[[  1.   2.  -1.  -2.   2.]
 [  0.   0.  -1.   2.  -1.]
 [  0.   0.   1.  -2.   2.]
 [  3.   6.  -1. -10.   9.]]


In [134]:
aa[3, :]-=aa[0, :]*3
print(aa)

[[ 1.  2. -1. -2.  2.]
 [ 0.  0. -1.  2. -1.]
 [ 0.  0.  1. -2.  2.]
 [ 0.  0.  2. -4.  3.]]


In [135]:
aa[1, :]=aa[1, :]*(-1)
print(aa)

[[ 1.  2. -1. -2.  2.]
 [-0. -0.  1. -2.  1.]
 [ 0.  0.  1. -2.  2.]
 [ 0.  0.  2. -4.  3.]]


In [136]:
aa[2, :]-=aa[1, :]
print(aa)

[[ 1.  2. -1. -2.  2.]
 [-0. -0.  1. -2.  1.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  0.  2. -4.  3.]]


In [137]:
aa[3, :]-=aa[1,:]*2
print(aa)

[[ 1.  2. -1. -2.  2.]
 [-0. -0.  1. -2.  1.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  1.]]


이를 보아 이 연립방정식의 해는 무수히 많다.
미지수는 4개이나 식은 두개 밖에 없기 때문이다.