In [1]:
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
%matplotlib widget
import matplotlib.pyplot as plt

## 과제 1. x = (sqrt(3), 1), y = (0, 2) 일때 다음을 실행

> (A) 벡터 x = (sqrt(3), 1), y = (0, 2)에 대해 다음 계산

In [2]:
#1. 2x - 3y
x = np.array([np.sqrt(3), 1])
y = np.array([0, 2])
print(2*x-3*y)

[ 3.46410162 -4.        ]


In [3]:
#2. x의 크기
np.linalg.norm(x)

1.9999999999999998

> (B) 두 벡터 x = (1, -2, -3 ), y = (5, -4, -3) 에 대해 다음 계산

In [4]:
#1. ||x+y||
x = np.array([1, -2 ,-3])
y = np.array([5, -4, -3])
np.linalg.norm(x+y)

10.392304845413264

In [5]:
#2. ||x-y||
np.linalg.norm(x-y)

4.47213595499958

In [6]:
#3. ||x||+||y||
np.linalg.norm(x)+np.linalg.norm(y)

10.812725198639416

> (C) 다음 벡터 x 에서 y 로의 직교정사영 구하기

In [7]:
#1.
x = np.array([-1, -2])
y = np.array([-2, 3])
np.dot(x, y)*y/np.square((np.linalg.norm(y)))

array([ 0.61538462, -0.92307692])

In [8]:
#2.
x = np.array([3, 1, -7])
y = np.array([1, 0, 5])
np.dot(x, y)*y/np.square((np.linalg.norm(y)))

array([-1.23076923,  0.        , -6.15384615])

## 과제 2. 다음을 구하여라.

In [9]:
#1. i = (1, 0, 0), j = (0, 1, 0) 일 때 z = i x j 와 w = j x i 를 구하여라
i = np.array([1, 0, 0])
j = np.array([0, 1, 0])
z = np.cross(i, j)
w = np.cross(j, i)
print(z, w)

[0 0 1] [ 0  0 -1]


In [10]:
#2. i, j, z, w 를 한 그림으로 그려라
ax=plt.gca(projection='3d')
ax.set_xlim(-2, 2)
ax.set_ylim(-2, 2)
ax.set_zlim(-2, 2)
ax.quiver(0,0,0, i[0], i[1], i[2], color='k')
ax.quiver(0,0,0, j[0], j[1], j[2], color='y')
ax.quiver(0,0,0, z[0], z[1], z[2], color='r')
ax.quiver(0,0,0, w[0], w[1], w[2], color='b')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [100]:
#3. 그림 부분에서 mouse를 drag하여 vector를 회전하면서 
#i, j와 z, w와의 관계를 관찰하고, k = (0, 0, 1)와 z, w와의 관계를 써라.

i 가 노랑색, j 가 검정색 그리고 z 와 w 는 각각 빨강, 파랑이다.
이때 i 와 j 는 z = 0 인 동일 평면에 존재한다
또한 z 와 w 는 크기는 같으나 방향이 정반대이다.(z+w => 0)

k = (0, 0, 1) 일 때 z 도 (0, 0, 1) 이므로 k 와 크기와 방향이 같은 벡터이다.
또한, w 는 (0, 0, -1) 이므로 k와 크기는 같으나 방향이 정반대이다.

## 과제 3. 4개의 점 A, B, C, D 로 다음을 풀어라
> A = (0, 0), B = (1, 2), C = (5, 2), D = (3, 3)

In [120]:
#(A) 삼각형 ABC 의 면적을 벡터의 외적을 이용하여 구해라
A = np.array([0, 0])
B = np.array([1, 2])
C = np.array([5, 2])
D = np.array([3, 3])

tri1 = np.linalg.norm(np.cross(B, C))/2
print(tri1)

4.0


In [121]:
#(B) 사각형 ABCD 의 면적을 벡터의 외적을 이용하여 구해라
x = C - B
y = D - B

tri2 = np.linalg.norm(np.cross(x, y))/2
print(tri1+tri2)

6.0


## 과제 4. 다음을 구하여라.

### (1) 두점 (1, 1, 1) 과 (2, 3, 4) 를 지나는 직선의 방정식을 구하라

u = (2, 3, 4) - (1, 1, 1) = (1, 2, 3)

(x, y, z) = (1, 1, 1) + t(1, 2, 3)

(x-1)/1 = (y-1)/2 = (z-1)/3

### (2) 평면 3x - 2y + z = 5 와 직선 x = 1+t, y = -2+2t, z = 4t 가 만나는 점을 구하여라

3(1+t)-2(-2+2t)+4t = -5

3t = -12

t = -4

x = -3, y = -10, z = -16

### (3) 점 (2, 3, 5) 와 평면 x-2y+2z+3 = 0 사이의 거리를 구하라

In [110]:
u = np.array([1, -2, 2])
d = np.abs(2*u[0] + 3*u[1] + 5*u[2] + 3)/np.linalg.norm(u)
print(d)

3.0
