In [1]:
import numpy as np

In [2]:
2*3

6

In [3]:
a=2*3

In [4]:
a

6

In [3]:
A=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(A)
print(A.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [6]:
A.shape

(3, 3)

In [8]:
#우아ㅏ앙

### 행렬
# :D
<img src="https://images.unsplash.com/photo-1481819613568-3701cbc70156?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80" width="25%">

In [9]:
A[1,:]

array([4, 5, 6])

In [10]:
A[0,:]

array([1, 2, 3])

In [12]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.diag(A)

array([1, 5, 9])

In [4]:
np.diag(np.diag(A))

array([[1, 0, 0],
       [0, 5, 0],
       [0, 0, 9]])

In [2]:
A=np.array([[7, -3], [2, 0]])

In [3]:
print(A)

[[ 7 -3]
 [ 2  0]]


In [5]:
print(A.T)

[[ 7  2]
 [-3  0]]


In [6]:
B=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [7]:
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
print(B.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [9]:
C=np.array([[0,1,2,3],[4,5,6,7]])

In [10]:
print(C)

[[0 1 2 3]
 [4 5 6 7]]


In [11]:
print(C.T)

[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [12]:
D=np.array([[0,1,2,3],[4,5,6,7],[8,9,10,11]])

In [13]:
print(D)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [14]:
print(D.T)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [1]:
import numpy as np

In [2]:
A=np.array([[2, -8, 6, 8], [3, -9, 5, 10], [-3, 0, 1, -2], [1, -4, 0, 6]])

In [3]:
A

array([[ 2, -8,  6,  8],
       [ 3, -9,  5, 10],
       [-3,  0,  1, -2],
       [ 1, -4,  0,  6]])

In [4]:
np.linalg.det(A)

-36.000000000000014