In [1]:
import numpy as np
import numpy.linalg as la
%matplotlib qt
import matplotlib.pyplot as plt

### 벡터의 정의와 연산
벡터는 크기와 방향이 있고 표시할 때 시점이 다를 수 있다.
즉 다음 두 벡터 $\vec{AB}$ 와 $\vec{CD}$는 같다

In [2]:
B=np.array([1,2])
A=np.array([2,1])

In [3]:
plt.close()
ax=plt.gca()

In [4]:
args={"angles":"xy","scale":1,"scale_units":"xy"}
ax.quiver(A[0],A[1],D[0],D[1],**args)
ax.quiver(C[0],C[1],D[0],D[1],**args)
ax.set_xlim((-2,4))
ax.set_ylim((-2,4))
ax.text(A[0]-0.2,A[1]-0.2,'A')
ax.text(B[0]+0.2,B[1]+0.2,'B')
ax.text(C[0]-0.2,C[1]-0.2,'C')
ax.text(D[0]+0.2,D[1]+0.2,'D')
ax.axhline(0, color='g')
ax.axvline(0, color='g')
ax.set_aspect('equal')

NameError: name 'D' is not defined

벡터의 크기는 norm이라하고 다음과 같이 표현한다

2D: $\sqrt{x_1^2 + x_2^2}$

3D: $\sqrt{x_1^2 + x_2^2 + x_3^2}$

In [ ]:
ax.grid()

In [ ]:
ax.quiver(B[0],B[1],**args, color='r')

In [5]:
x=np.array([2,-3,5])

In [6]:
print(x)

[ 2 -3  5]


In [7]:
print(np.sqrt(x[0]**2+x[1]**2+x[2]**2))

6.164414002968976


In [8]:
la.norm(x)

6.164414002968976

### 벡터합과 스칼라곱

In [9]:
plt.close()

In [10]:
x=np.array([4,5])
y=np.array([-1,3])
ax=plt.gca()
ax.quiver(0,0,x[0],x[1],**args)
ax.text(x[0],x[1],'x')
ax.quiver(0,0,y[0],y[1],**args)
ax.text(y[0],y[1],'y')
ax.quiver(0,0,(x+y)[0],(x+y)[1],**args,color='b')
ax.text((x+y)[0],(x+y)[1],'x+y')
ax.set_xlim((-2,5))
ax.set_ylim((-1,10))
ax.axhline(0, color='g')
ax.axvline(0, color='g')
ax.quiver(y[0],y[1],x[0],x[1],**args,color='y')
ax.quiver(x[0],x[1],y[0],y[1],**args,color='y')
ax.quiver(0,0,(x+y)[0],(x+y)[1],**args,color='b')
ax.set_aspect('equal')

두 벡터사이의 거리는 두벡터의 시점을 원점에 두고 종점간의 거리이다. 

2D: $\Vert x-y \Vert = \sqrt{(x_1 - y_1)^2 + (x_2 - y_2)^2}$

3D: $\Vert x-y \Vert = \sqrt{(x_1 - y_1)^2 + (x_2 - y_2)^2 + (x_3 - y_3)^2}$

In [11]:
x=np.array([2,-1,4])
y=np.array([3,1,6])

In [12]:
la.norm(x-y)

3.0

In [13]:
print(x-y)

[-1 -2 -2]


In [14]:
plt.close()

표준단위벡터

In [15]:
i=np.array([1,0])
j=np.array([0,1])
ax=plt.gca()
ax.quiver(i[0],i[1],**args,color='b')
ax.quiver(j[0],j[1],**args,color='b')
ax.set_xlim((-1,2))
ax.set_ylim((-1,2))
ax.grid()
ax.set_aspect('equal')

In [16]:
x=np.array([3,5])
print(x)

[3 5]


In [17]:
xd=3*i+5*j
print(xd)

[3 5]


### 벡터의 내적

In [18]:
x=np.array([1,3,-2])
y=np.array([-2,2,7])

In [19]:
np.dot(x,y)

-10

In [20]:
print(x[0]*y[0]+x[1]*y[1]+x[2]*y[2])

-10


In [21]:
i=np.array([1,0,0])
j=np.array([0,1,0])
k=np.array([0,0,1])

In [22]:
print(np.dot(i,i))
print(np.dot(i,j))

1
0


In [23]:
plt.close()

두 벡터가 이루는 각

In [24]:
x=np.array([1,0])
y=np.array([2,2])
ax=plt.gca()
ax.quiver(x[0],x[1],**args)
ax.quiver(y[0],y[1],**args)
ax.set_xticks(range(-1,4))
ax.set_yticks(range(-1,4))
ax.grid()
ax.set_aspect('equal')

In [25]:
c=np.dot(x,y)/(la.norm(x)*la.norm(y))
print(c)

0.7071067811865475


In [26]:
c=np.dot(x,y)/(la.norm(x)*la.norm(y))

In [27]:
print(np.arccos(c)/3.14*180)

45.02282465335691


In [28]:
np.arccos(c)*180/np.pi

45.00000000000001

## **직교정사영**

- x 벡터의 y 벡터로의 정사영은 x의 y방향 성분을 말하고 $proj_\bf{y}\bf{x}$ 라고 쓴다
- $proj_\bf{y}\bf{x}$  방향의 단위벡터는 $\bf{y}$ 벡터를 그 크기로 나눈것과 같다. 즉 $\frac{\bf{y}}{\Vert\bf{y}\Vert}$ 이다
- $proj_\bf{y}\bf{x}$ 의 크기는 $\bf{x}$ 와 $\bf{y}$ 벡터 방향의 단위벡터와 내적한 것과 같다. 즉  $\Vert proj_\bf{y}\bf{x}\Vert = \bf{x} \cdot \frac{\bf{y}}{\Vert\bf{y}\Vert}$   

<a><img src="projection.png" width="400"></a>

In [29]:
x=np.array([2, 2])
y=np.array([3, 1])

In [30]:
z=np.dot(x,y/la.norm(y))*y/la.norm(y)
print(z)

[2.4 0.8]


In [31]:
plt.close()

In [32]:
ax=plt.gca()
ax.quiver(x[0],x[1],**args)
ax.quiver(y[0],y[1],**args)
ax.quiver(z[0],z[1],**args,color='b')
h=z-x
ax.quiver(x[0],x[1],h[0],h[1],**args,color='y')
ax.set_xticks(range(-1,4))
ax.set_yticks(range(-1,4))
ax.grid()
ax.set_aspect('equal')

In [33]:
print(np.arccos(np.dot(z,h)/(la.norm(z)*la.norm(h)))/np.pi*180)

90.00000000000001


## **벡터의 외적** 
   
$\begin{aligned}
\mathbf{x} \times \mathbf{y} & = \begin{vmatrix}
\mathbf{i} & \mathbf{j} & \mathbf{k} \\
x_1 & x_2 & x_3 \\
y_1 & y_2 & y_3 \\
\end{vmatrix} \\ \\
 & = \begin{vmatrix}
x_2 & x_3 \\
y_2 & y_3 \\
\end{vmatrix} \mathbf{i} -
\begin{vmatrix}
x_1 & x_3 \\
y_1 & y_3 \\
\end{vmatrix} \mathbf{j} +
\begin{vmatrix}
x_1 & x_2 \\
y_1 & y_2 \\
\end{vmatrix} \mathbf{k} \\ \\
& = (x_2 y_3 - x_3 y_2 ) \mathbf{i} - (x_1 y_3 - x_3 y_1 ) \mathbf{j} + (x_1 y_2 - x_2 y_1 ) \mathbf{k}
\end{aligned}$

In [34]:
x=np.array([-2, 1, 0])
y=np.array([0, 3, 0])

In [35]:
np.cross(x,y)

array([ 0,  0, -6])

In [36]:
x=np.array([-2, 3, 0])
y=np.array([3, 0, 1])

In [37]:
np.cross(x,y)

array([ 3,  2, -9])

단위벡터의 외적

In [38]:
i=np.array([1,0,0])
j=np.array([0,1,0])
k=np.array([0,0,1])

In [39]:
np.cross(i,i)

array([0, 0, 0])

In [40]:
np.cross(i,j)

array([0, 0, 1])

In [41]:
np.cross(j,i)

array([ 0,  0, -1])

In [42]:
np.cross(k,j)

array([-1,  0,  0])

3차원에서 두 벡터에 모두 수직인 벡터

In [43]:
x=np.array([-2,3,0])
y=np.array([1,1,-1])
z=np.cross(x,y)

from mpl_toolkits.mplot3d import axes3d
ax = plt.gca(projection='3d')

vts = np.vstack((x,y,z))
colors=['r','g','b']
ax.quiver(np.zeros(3),np.zeros(3),np.zeros(3),vts[:,0],vts[:,1],vts[:,2],color=colors)
mv=np.max(np.abs(vts))
ax.set_xlim(-mv,mv)
ax.set_ylim(-mv,mv)
ax.set_zlim(-mv,mv)
ax.text(x[0],x[1],x[2],'x')
ax.text(y[0],y[1],y[2],'y')
ax.text(z[0],z[1],z[2],'z')

C:\Users\plane\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: UserWarning: Requested projection is different from current axis projection, creating new axis with requested projection.
  
C:\Users\plane\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  


Text(-3, -2, 'z')

In [44]:
print(vts)
np.max(np.abs(vts))

[[-2  3  0]
 [ 1  1 -1]
 [-3 -2 -5]]


5

### 벡터곱의 크기 (벡터곱 = 외적 = cross product)

<a><img src="unitInnerOuter.png" width="200" align="left"></a> 사이각 $\theta = \beta - \alpha$

- $\mathbf{u} = (x_1 , x_2 ) = (\cos \alpha , \sin \alpha )$

- $\mathbf{v} = (y_1 , y_2 ) =  (\cos \beta , \sin \beta )$

### **내적** (inner product)
- $\mathbf{u} \cdot \mathbf{v} = x_1 y_1 + x_2 y_2 = \cos \beta \cos \alpha + \sin \beta \sin \alpha = \cos ( \beta - \alpha) = \cos \theta$

### **외적** (outer product, vector product, cross product)
    

- $\begin{equation*}
\mathbf{u} = x_1 \mathbf{i} + x_2 \mathbf{j} \\
\mathbf{v} = y_1 \mathbf{i} + y_2 \mathbf{j}
\end{equation*}$
    

- $\begin{align}
\mathbf{u} \times \mathbf{v} & = \begin{vmatrix}
\mathbf{i} & \mathbf{j} & \mathbf{k} \\
x_1 & x_2 & 0 \\
y_1 & y_2 & 0 \\
\end{vmatrix} \\ 
& = (x_1 y_2 - x_2 y_1 ) \mathbf{k} \\ 
& = (\cos \alpha \sin \beta - \cos \beta \sin \alpha ) \\ 
& = \sin \theta
\end{align}$
    

In [45]:
np.cross(x,y)

array([-3, -2, -5])

In [46]:
A=np.array([2, -1, 0])
B=np.array([3, 0, 1])
C=np.array([0, 2, -1])

### 외적의 기하학적 의미

<img src="crossProduct.png" width=400>

$\Vert \mathbf{x} \times \mathbf{y} \Vert = \Vert \mathbf{x}\Vert \Vert \mathbf{y}\Vert \Vert \mathbf{u}_\mathbf{x} \times \mathbf{u}_\mathbf{y} \Vert = \Vert \mathbf{x}\Vert \Vert \mathbf{y}\Vert\sin \theta$

---
(example) 세꼭지점이 $A=(2,-1,0)$, $B=(3,0,1)$, $C=(0,2,-1)$ 인 평행 사변형의 넓이는?

<img src="평행사변형넓이.jpg" width=300>

In [47]:
x=B-A
y=C-A
print(x,y)

[1 1 1] [-2  3 -1]


In [48]:
la.norm(np.cross(x,y))

6.48074069840786

### 스칼라 삼중적

$\mathbf{x} \cdot (\mathbf{y} \times \mathbf{z}) = \begin{vmatrix}
x_1 & x_2 & x_3 \\
y_1 & y_2 & y_3 \\
z_1 & z_2 & z_3 \\
\end{vmatrix}$

<img src="scalarTripleProd.png" width=400>

<a><img src="평행육면체.png" width=400></a>

- 밑면적: $\Vert \mathbf{y} \times \mathbf{z} \Vert$
- 높이: $\Vert \mathbf{x}\Vert\cos \theta = \Vert \mathbf{x}\Vert\mathbf{u}_\mathbf{x} \cdot \mathbf{u}_{\mathbf{y} \times \mathbf{z}} = \Vert \mathbf{x}\Vert \frac{\mathbf{x} \cdot (\mathbf{y} \times \mathbf{z})}{\Vert \mathbf{x}\Vert \Vert \mathbf{y} \times \mathbf{z} \Vert }$
- 부피: $\mathbf{y} \times \mathbf{z} \Vert \Vert \mathbf{x} \Vert \cos \theta = \mathbf{x} \cdot (\mathbf{y} \times \mathbf{z})$

In [49]:
x=np.array([2, -3, -4])
y=np.array([1, 2, 5])
z=np.array([1, 0, -3])

In [50]:
la.det(np.array([x,y,z]))

-28.00000000000001

---
시점이 같은 세벡터가 동일 평면상에 있을 필요 충분 조건 = 스칼라 삼중적이 0

$\mathbf{x} \cdot (\mathbf{y} \times \mathbf{z}) = 0$

In [51]:
x=np.array([2, -3, 9])
y=np.array([3, -2, 5])
z=np.array([-4, 1, -1])

In [52]:
la.det(np.array([x,y,z]))

0.0

## 벡터 삼중적

$\mathbf{x} \times (\mathbf{y} \times \mathbf{z})$

**properties**
- $\mathbf{x} \times (\mathbf{y} \times \mathbf{z}) + \mathbf{y} \times (\mathbf{z} \times \mathbf{x}) + \mathbf{z} \times (\mathbf{x} \times \mathbf{y}) = 0$
- $\mathbf{x} \times (\mathbf{y} \times \mathbf{z}) \neq (\mathbf{x} \times \mathbf{y}) \times \mathbf{z}$ 


In [53]:
i=np.array([1,0,0])
j=np.array([0,1,0])
k=np.array([0,0,1])

In [54]:
np.cross(np.cross(i,j),j)

array([-1,  0,  0])

In [55]:
np.cross(i,np.cross(j,j))

array([0, 0, 0])

### 직선의 방정식

<img src="lineEquation.png" width=400>

- $P_0 (\mathbf{x}_0)$ 를 지나고 $\mathbf{u}$ 에 평행한 직선 $L$
- $\mathbf{x} - \mathbf{x}_0 = t \mathbf{u}$

In [56]:
#linspace 사용법
ax=plt.gca()
ax.set_xlim(-2,2)
ax.set_ylim(-2,2)
x=np.linspace(-2,2,100)
y=x
ax.scatter(x,y,c='b')
ax.grid()

In [57]:
plt.close()

In [58]:
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import numpy as np
from sympy import *
import numpy.linalg as la
#%matplotlib

두점 (3,4)과 (-4,5)를 지나는 직선의 방정식 $ \mathbf{x} = \mathbf{x_0} + t \mathbf{u}$ 를 구하고 매개 변수 $t$ 여러 값에 따라 생기는 직선상의 점들을 끝점으로 하는 벡터들을 구해 본다.

In [59]:
A=np.array([3,4])
B=np.array([-4,5])
x0=A       
u=(B-A)/la.norm(B-A) #직선 방향의 단위벡터

이상으로부터 x0를 지나고 u에 나란한 직선의 방정식은 x0+t*u 이다

In [60]:
x=np.vstack((x0+t*u for t in range(-5,6)))
x.shape

C:\Users\plane\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  """Entry point for launching an IPython kernel.


(11, 2)

In [61]:
x

array([[ 7.94974747,  3.29289322],
       [ 6.95979797,  3.43431458],
       [ 5.96984848,  3.57573593],
       [ 4.97989899,  3.71715729],
       [ 3.98994949,  3.85857864],
       [ 3.        ,  4.        ],
       [ 2.01005051,  4.14142136],
       [ 1.02010101,  4.28284271],
       [ 0.03015152,  4.42426407],
       [-0.95979797,  4.56568542],
       [-1.94974747,  4.70710678]])

In [62]:
arg={'angles':'xy', 'scale_units':'xy','scale':1,'color':'blue'}

In [63]:
ax=plt.gca()
ax.quiver(np.zeros(len(x)),np.zeros(len(x)),x[:,0],x[:,1],**arg)
ax.set_xlim(np.min(x[:,0]),np.max(x[:,0]))
ax.set_ylim(np.min([0,np.min(x[:,1])]),np.max(x[:,1]))

(0.0, 4.707106781186548)

In [64]:
plt.close()

In [65]:
plt.plot(x[:,0],x[:,1],'bo')

plt.plot(A[0],A[1],'r+')
plt.plot(B[0],B[1],'r+')
plt.show()


In [66]:
arg={'angles':'xy', 'scale_units':'xy','scale':1,'color':'blue'}
plt.quiver(0,0,x[:,0],x[:,1],**arg)

In [67]:
tl=np.linspace(-5,6,100)

In [68]:
x=np.vstack((x0+t*u for t in tl))

C:\Users\plane\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  """Entry point for launching an IPython kernel.


In [69]:
x.shape

(100, 2)

In [70]:
plt.plot(x[:,0],x[:,1],'b.')
plt.plot(A[0],A[1],'ro')
plt.plot(B[0],B[1],'ro')

In [71]:
plt.close()

### 평면의 방정식

<img src="평면방정식.png" width=300>

- $P_0 (\mathbf{x}_0 )$ 를 지나고 $\mathbf{n}$ 에 수직인 평면 $\alpha$
- $ (\mathbf{x} - \mathbf{x}_0 ) \cdot \mathbf{n} = 0$
- $\mathbf{n} = (a,b,c)$ 이면 $a(x-x_0)+b(y-y_0)+c(z-z_0)=0$ 이다
- 즉 $ax+by+cz=\mathbf{n} \cdot \mathbf{x_0}$ 이다.
- 그러므로 $(x_v,y_v)$가 주어지면 $z_v=\frac1c (\mathbf{n} \cdot \mathbf{x_0}-ax_v -by_v)$ 로 구할 수 있다

---
(example) 점 (3,-1,4) 를 포함하고 $\mathbf{n}=(-2,8,2)$ 에 수직인 평면

In [72]:
x0=np.array([3, -1, 4])
n=np.array([-2, 8, 2])

In [73]:
xv, yv = np.meshgrid(range(x0[0]-5,x0[0]+6),range(x0[1]-5,x0[1]+6))

In [74]:
sz=xv.shape
zv=np.zeros(sz)

In [75]:
for i in range(sz[1]):
    for j in range (sz[0]):
        zv[j,i]=1/n[2]*(np.dot(x0,n)-n[0]*xv[j,i]-n[1]*yv[j,i])

In [76]:
ax=plt.gca(projection='3d')
ax.scatter(xv,yv,zv,'b')
ax.quiver(x0[0],x0[1],x0[2],n[0],n[1],n[2],color='r')
M=np.max([np.max(xv),np.max(yv),np.max(zv)])
m=np.min([np.min(xv),np.min(yv),np.min(zv)])
ax.set_xlim(m,M)
ax.set_ylim(m,M)
ax.set_zlim(m,M)

(-21.0, 29.0)