In [1]:
import numpy as np

In [2]:
A=np.array([[0, -1, -1, 1], [2, 2, 2, 2], [2, 4, 1, -2], [3, 1, -2, 2]])
B=np.array([[0],[12],[-1],[3]])
aug = np.column_stack((A, B))
print(aug)

[[ 0 -1 -1  1  0]
 [ 2  2  2  2 12]
 [ 2  4  1 -2 -1]
 [ 3  1 -2  2  3]]


In [3]:
temp = np.copy(aug[0, :])
aug[0, :] = aug[1, :]
aug[1, :] = temp
aug

array([[ 2,  2,  2,  2, 12],
       [ 0, -1, -1,  1,  0],
       [ 2,  4,  1, -2, -1],
       [ 3,  1, -2,  2,  3]])

In [4]:
aug[0, :]= (1/2)*aug[0, :]
aug

array([[ 1,  1,  1,  1,  6],
       [ 0, -1, -1,  1,  0],
       [ 2,  4,  1, -2, -1],
       [ 3,  1, -2,  2,  3]])

In [5]:
aug[2, :]=(-2)*aug[0, :]+aug[2, :]
aug

array([[  1,   1,   1,   1,   6],
       [  0,  -1,  -1,   1,   0],
       [  0,   2,  -1,  -4, -13],
       [  3,   1,  -2,   2,   3]])

In [6]:
aug[3, :]+=(-3)*aug[0, :]
aug

array([[  1,   1,   1,   1,   6],
       [  0,  -1,  -1,   1,   0],
       [  0,   2,  -1,  -4, -13],
       [  0,  -2,  -5,  -1, -15]])

In [7]:
aug[2, :]+=aug[1,:]*2
aug

array([[  1,   1,   1,   1,   6],
       [  0,  -1,  -1,   1,   0],
       [  0,   0,  -3,  -2, -13],
       [  0,  -2,  -5,  -1, -15]])

In [8]:
aug[3, :]+=(-2)*aug[1, :]
aug

array([[  1,   1,   1,   1,   6],
       [  0,  -1,  -1,   1,   0],
       [  0,   0,  -3,  -2, -13],
       [  0,   0,  -3,  -3, -15]])

In [9]:
aug[3, :]+=(-1)*aug[2, :]
aug

array([[  1,   1,   1,   1,   6],
       [  0,  -1,  -1,   1,   0],
       [  0,   0,  -3,  -2, -13],
       [  0,   0,   0,  -1,  -2]])

In [10]:
x4 = aug[3, 4]/aug[3, 3]
x3 = (aug[2, 4]+2*x4)/aug[2, 2]
x2 = (x3 - x4)/aug[1, 1]
x1 = 6 - x2 - x3 - x4
print(np.array([[x1], [x2], [x3], [x4]]))

[[ 2.]
 [-1.]
 [ 3.]
 [ 2.]]


In [11]:
r, c = np.shape(aug)
a=np.copy(aug[:, 0:c-1])
b=np.copy(aug[:, -1])
print(a, b)

[[ 1  1  1  1]
 [ 0 -1 -1  1]
 [ 0  0 -3 -2]
 [ 0  0  0 -1]] [  6   0 -13  -2]


In [12]:
n=c-1
x=np.zeros((n, 1))
for i in range(n-1, -1, -1):
    x[i]=(b[i]-np.dot(a[i, :], x))/a[i, i]
print(x)

[[ 2.]
 [-1.]
 [ 3.]
 [ 2.]]


In [13]:
c=np.array([[1, -1, 1], [1, 0, 2], [-1, 1, -1], [2, -2, 2]])
d=np.array([[-1], [1], [0], [-1]])
Aug=np.column_stack((c, d))
Aug

array([[ 1, -1,  1, -1],
       [ 1,  0,  2,  1],
       [-1,  1, -1,  0],
       [ 2, -2,  2, -1]])

In [3]:
from sympy import *

In [18]:
Matrix(Aug).rref()

(Matrix([
 [1, 0, 2, 0],
 [0, 1, 1, 0],
 [0, 0, 0, 1],
 [0, 0, 0, 0]]), (0, 1, 3))

In [5]:
neno = np.zeros((5, 5))
print(neno)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [6]:
neno.shape

(5, 5)

In [7]:
np.shape(neno)

(5, 5)

In [10]:
nemo = np.eye(5)
print(nemo)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [13]:
print(nemo[ 0 : 3, 1])

[0. 1. 0.]


In [14]:
print(nemo[-1, :])

[0. 0. 0. 0. 1.]


In [15]:
nn = np.array([[0], [1], [2], [3], [4]])
print(nemo, nn)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] [[0]
 [1]
 [2]
 [3]
 [4]]


In [2]:
test = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
test

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
test[1, :]

array([4, 5, 6])

In [4]:
test[:, 2]

array([3, 6, 9])

In [5]:
test[1:2, 2:3]

array([[6]])

In [6]:
test[0:1, 1:2]

array([[2]])

In [2]:
A = np.array([0, 3, 4])
B = np.array([-1, 1, 2])
C = np.array([6, 1, 8])

In [3]:
x = B - A
y = C - A
print(x)
print(y)

[-1 -2 -2]
[ 6 -2  4]


In [4]:
print(np.linalg.norm(np.cross(x, y))/2)

10.04987562112089


In [6]:
A = np.array([[3, -5, -3], [6, -2, 0], [-8, 4, 1]])
x = np.array([[1], [3], [-4]])
Aug = np.column_stack((A, x))
print(Aug)

[[ 3 -5 -3  1]
 [ 6 -2  0  3]
 [-8  4  1 -4]]


In [7]:
Matrix(Aug).rref()

(Matrix([
 [1, 0, 1/4, 0],
 [0, 1, 3/4, 0],
 [0, 0,   0, 1]]), (0, 1, 3))

In [9]:
print(Matrix(np.array([[1, 4, 5, 2], [2, 1, 3, 0], [-1, 3, 2, 2]])).nullspace())

[Matrix([
[-1],
[-1],
[ 1],
[ 0]]), Matrix([
[ 2/7],
[-4/7],
[   0],
[   1]])]


In [10]:
print(Matrix(np.array([[1, -2, 0, 4, 0], [0, 0, 1, 9, 0], [0, 0, 0, 0, 1]])).nullspace())

[Matrix([
[2],
[1],
[0],
[0],
[0]]), Matrix([
[-4],
[ 0],
[-9],
[ 1],
[ 0]])]


In [4]:
print(Matrix(np.array([[4, -2, 7], [0, 5, 2], [-2, 1, 3]])).rref())

(Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]]), (0, 1, 2))


In [1]:
import numpy as np
from sympy import *

In [2]:
print(Matrix(np.array([[2, 0, 2, 3], [7, 6, -5, 0], [6, 8, -10, -5]])).rref())

(Matrix([
[1, 0,  1,  3/2],
[0, 1, -2, -7/4],
[0, 0,  0,    0]]), (0, 1))


In [5]:
print(Matrix(np.array([[1, 3, -2, 4, 5], [2, 1, 1, 3, 1], [5, 2, 3, 7, 3], [10, 5, 5, 15, 7]])).rref())

(Matrix([
[1, 0,  1, 1, 0],
[0, 1, -1, 1, 0],
[0, 0,  0, 0, 1],
[0, 0,  0, 0, 0]]), (0, 1, 4))


In [6]:
print(Matrix(np.array([[1, 2, 5, 10], [3, 1, 2, 5], [-2, 1, 3, 5], [4, 3, 7, 15], [5, 1, 3, 7]]).T).rref())

(Matrix([
[1, 0,  1, 1, 0],
[0, 1, -1, 1, 0],
[0, 0,  0, 0, 1],
[0, 0,  0, 0, 0]]), (0, 1, 4))


In [10]:
A = np.array([[1,0,2,3], [-1, 2, 5, 3], [-1, 1, 0, 2]]).T
print(Matrix(A).rref())
print(Matrix(A).rank())

(Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1],
[0, 0, 0]]), (0, 1, 2))
3


In [12]:
B1 = np.array([[-5], [6], [11], [3]])
ab = np.column_stack((A, B1))
print(ab)
print(Matrix(ab).rref())
print(Matrix(ab).rank())

[[ 1 -1 -1 -5]
 [ 0  2  1  6]
 [ 2  5  0 11]
 [ 3  3  2  3]]
(Matrix([
[1, 0, 0, -2],
[0, 1, 0,  3],
[0, 0, 1,  0],
[0, 0, 0,  0]]), (0, 1, 2))
3


In [13]:
B2 = np.array([[5], [2], [4], [-7]])
AB = np.column_stack((A, B2))
print(AB)
print(Matrix(AB).rref())
print(Matrix(AB).rank())

[[ 1 -1 -1  5]
 [ 0  2  1  2]
 [ 2  5  0  4]
 [ 3  3  2 -7]]
(Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1]]), (0, 1, 2, 3))
4


In [18]:
X = np.array([[1, 0, -3 , 2], [0, 1, 2, -3], [-3, -4, 1, 6], [1, -3, -8, 7], [2, 1, -6, 9]]).T
x = np.array([[1, 0, -3 , 2], [0, 1, 2, -3], [-3, -4, 1, 6], [1, -3, -8, 7], [2, 1, -6, 9]])
print(Matrix(X).rref())
print(Matrix(X).rank())
print(Matrix(X).nullspace())
print(Matrix(x).rref())
print(Matrix(x).rank())

(Matrix([
[1, 0, -3, 0,  4],
[0, 1, -4, 0, -5],
[0, 0,  0, 1, -2],
[0, 0,  0, 0,  0]]), (0, 1, 3))
3
[Matrix([
[3],
[4],
[1],
[0],
[0]]), Matrix([
[-4],
[ 5],
[ 0],
[ 2],
[ 1]])]
(Matrix([
[1, 0, 0, -10],
[0, 1, 0,   5],
[0, 0, 1,  -4],
[0, 0, 0,   0],
[0, 0, 0,   0]]), (0, 1, 2))
3


In [17]:
X = np.array([[2, 1, -4, 1], [3, -1, 2, 1], [3, 0, -2, 2], [5, -1, -4, 3], [8, -1, -6, 5]]).T
print(Matrix(X).rref())
print(Matrix(X).rank())
print(Matrix(X).nullspace())

(Matrix([
[1, 0, 0, 0, 0],
[0, 1, 0, 0, 0],
[0, 0, 1, 0, 1],
[0, 0, 0, 1, 1]]), (0, 1, 2, 3))
4
[Matrix([
[ 0],
[ 0],
[-1],
[-1],
[ 1]])]


In [19]:
A = np.array([[3, -1, 2, 5], [4, 7, -5, 3], [2, 5, 3, 6], [2, 9, 5, -4]])
b = np.array([10, -46, -1, 35]).T

print(Matrix(np.column_stack((A, b))).rref())

(Matrix([
[1, 0, 0, 0,  3],
[0, 1, 0, 0, -2],
[0, 0, 1, 0,  7],
[0, 0, 0, 1, -3]]), (0, 1, 2, 3))


In [22]:
A = np.array([[2, 5, 6], [-3, 9, 8], [7, -4, 1]])
b = np.array([-8, 18, 13])
print(Matrix(A).rref())
print(Matrix(A).rank())
print(Matrix(np.column_stack((A.T, b.T))).rref())
print(Matrix(np.column_stack((A.T, b.T))).rank())

(Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]]), (0, 1, 2))
3
(Matrix([
[1, 0, 0,  1],
[0, 1, 0,  1],
[0, 0, 1, -1]]), (0, 1, 2))
3


In [23]:
A = np.array([[2, 5, 16], [-3, 9, 9], [7, -4, 13]])
b = np.array([-8, 18, 13])
print(Matrix(A).rref())
print(Matrix(A).rank())
print(Matrix(np.column_stack((A.T, b.T))).rref())
print(Matrix(np.column_stack((A.T, b.T))).rank())

(Matrix([
[1, 0, 3],
[0, 1, 2],
[0, 0, 0]]), (0, 1))
2
(Matrix([
[1, 0,  17/11, 0],
[0, 1, -43/33, 0],
[0, 0,      0, 1]]), (0, 1, 3))
3


In [24]:
A = np.array([[4, 5, -2, 6, 0], [1, 1, 0, 1, 0]])
print(Matrix(A).rref())

(Matrix([
[1, 0,  2, -1, 0],
[0, 1, -2,  2, 0]]), (0, 1))


In [26]:
A = np.array([[2, -2, 3], [4, -5, 7], [-2, 7, -8], [1, 3, 6]]).T
print(Matrix(A).rref())
print(Matrix(A).rank())

(Matrix([
[1, 0,  9, 0],
[0, 1, -5, 0],
[0, 0,  0, 1]]), (0, 1, 3))
3


In [34]:
A = np.array([[-2, 2, -3], [4, -6, 8], [-2, -3, 2], [-4, 1, -3]]).T
print(Matrix(A).rref())
print(np.array([[-2, 2, -3], [4, -6, 8], [-2, -3, 2], [-4, 1, -3]]))
print(Matrix(np.array([[-2, 2, -3], [4, -6, 8], [-2, -3, 2], [-4, 1, -3]])).rref())

(Matrix([
[1, 0,   6,   5],
[0, 1, 5/2, 3/2],
[0, 0,   0,   0]]), (0, 1))
[[-2  2 -3]
 [ 4 -6  8]
 [-2 -3  2]
 [-4  1 -3]]
(Matrix([
[1, 0, 1/2],
[0, 1,  -1],
[0, 0,   0],
[0, 0,   0]]), (0, 1))


In [33]:
A = np.array([[1, -4, 9, -7], [-1, 2, -4, 1], [5, -6, 10, 7]])
B = np.array([[1, 0, -1, 5], [0, -2, 5, -6], [0, 0, 0, 0]])

print(Matrix(A).rref())
print(Matrix(B.T).rref())
print(Matrix(A).nullspace())

(Matrix([
[1, 0,   -1, 5],
[0, 1, -5/2, 3],
[0, 0,    0, 0]]), (0, 1))
(Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 0],
[0, 0, 0]]), (0, 1))
[Matrix([
[  1],
[5/2],
[  1],
[  0]]), Matrix([
[-5],
[-3],
[ 0],
[ 1]])]


In [36]:
t = np.array([[5, 1, -7], [3, -2, 1], [-3, 1, 1]]).T
print(Matrix(t).rref())

(Matrix([
[1, 0, -3/13],
[0, 1, -8/13],
[0, 0,     0]]), (0, 1))


In [2]:
np.square(5)

25

In [3]:
A = np.array([[3, -1, 2, 5], [4, 7, -5, 3], [2, 5, 3, 6], [2, 9, 5, -4]])
print(Matrix(A).rref())
print(Matrix(A).nullspace())

(Matrix([
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1]]), (0, 1, 2, 3))
[]
