## $det(AB)=det(A)det(B)$
- ### 기본 행연산 (열연산을 포함한다.)
>1. replacement: 어떤 행을 그 행과 다른 행에 실수를 곱해서 더한 것으로 대체
>2. Interchange: 두 행을 서로 바꿈
>3. Scaling: 한 행에 0이 아닌 실수를 곱함

- **기본행렬**
> - dentity matrix에 기본행연산을 해서 만든 행렬
> - 어떤 행렬에 기본행렬을 곱하면 해당 행연산을 하는 효과를 보인다.

- ### $det(EA)=det(E)det(A)$
>- 기본 행렬과 곱의 determinant는 각각의 determinant의 곱과 같다. $\Leftarrow$ 정리 1.8과 1.9에 의하여
>> - 정리 1.8(2) interchange: A의 두 행을 교환한 행렬을 B라고 하면 $det(B)=-det(A)$
>> - 정리 1.9(1) scaling: A이 한 행에 상수 $k$를 곱해서 만든 행렬을 B라고 하고 하면 $det(B)=kdet(A)$
>> - 정리 1.9(3) replacement: A의 어떤 행을 그 행과 다른 행에 상수를 곱해서 만든 행으로 대체 한 행렬을 B라고 하면 $det(B)=det(A)$

- ### 기본행렬의 determinant
> - replacement: $E_r=\begin{bmatrix}1 & 0 & -3\\ 0 & 1 & 0\\ 0 & 0 & 1\end{bmatrix} \Leftarrow det(E_r)=1$
> - interchange: $E_i=\begin{bmatrix}0 & 1 & 0\\ 1&  0&  0\\ 0&  0&  1 \end{bmatrix} \Leftarrow det(E_i)=-1$ 
> - scaling: $E_s=\begin{bmatrix}1 & 0 & 0\\ 0 & 1 & 0\\ 0 & 0 & 2 \end{bmatrix} \Leftarrow det(E_s)=2$

## 예제
$A=\begin{bmatrix} 0 & 1 & 2\\1 & 0 & 3\\4 & -3 & 8 \end{bmatrix}$

$E_1=\begin{bmatrix}0 & 1 & 0\\ 1&  0&  0\\ 0&  0&  1 \end{bmatrix}$
$E_2=\begin{bmatrix}1 & 0 & 0\\ 0 & 1 & 0\\ -4 & 0 & 1\end{bmatrix}$
$E_3=\begin{bmatrix}1 & 0 & 0\\ 0 & 1 & 0\\ 0 & 3 & 1 \end{bmatrix}$
$E_4=\begin{bmatrix}1 & 0 & 0\\ 0 & 1 & 0\\ 0 & 0 & 0.5 \end{bmatrix}$
$E_5=\begin{bmatrix}1 & 0 & 0\\ 0 & 1 & –2\\ 0 & 0 & 1\end{bmatrix}$
$E_6=\begin{bmatrix}1 & 0 & -3\\ 0 & 1 & 0\\ 0 & 0 & 1\end{bmatrix}$

$E_1^{-1}=\begin{bmatrix}0 & 1 & 0\\ 1&  0&  0\\ 0&  0&  1 \end{bmatrix}$
$E_2^{-1}=\begin{bmatrix}1 & 0 & 0\\ 0 & 1 & 0\\ 4 & 0 & 1\end{bmatrix}$
$E_3^{-1}=\begin{bmatrix}1 & 0 & 0\\ 0 & 1 & 0\\ 0 & -3 & 1 \end{bmatrix}$
$E_4^{-1}=\begin{bmatrix}1 & 0 & 0\\ 0 & 1 & 0\\ 0 & 0 & 2 \end{bmatrix}$
$E_5^{-1}=\begin{bmatrix}1 & 0 & 0\\ 0 & 1 & 2\\ 0 & 0 & 1\end{bmatrix}$
$E_6^{-1}=\begin{bmatrix}1 & 0 & 3\\ 0 & 1 & 0\\ 0 & 0 & 1\end{bmatrix}$


In [1]:
import numpy as np

A=np.array([[0, 1, 2],[1, 0, 3],[4, -3, 8]])
E1=np.array([[0, 1, 0],[1, 0, 0],[0 ,0, 1]])
E2=np.array([[1, 0, 0],[0, 1, 0],[-4, 0, 1]])
E3=np.array([[1, 0, 0],[0, 1, 0],[0, 3, 1]])
E4=np.array([[1, 0, 0],[0, 1, 0],[0, 0, 0.5]])
E5=np.array([[1, 0, 0],[0, 1, -2],[0, 0, 1]])
E6=np.array([[1, 0, -3],[0, 1, 0],[0, 0, 1]])

e1=np.array([[0, 1, 0],[1, 0, 0],[0 ,0, 1]])
e2=np.array([[1, 0, 0],[0, 1, 0],[4, 0, 1]])
e3=np.array([[1, 0, 0],[0, 1, 0],[0, -3, 1]])
e4=np.array([[1, 0, 0],[0, 1, 0],[0, 0, 2]])
e5=np.array([[1, 0, 0],[0, 1, 2],[0, 0, 1]])
e6=np.array([[1, 0, 3],[0, 1, 0],[0, 0, 1]])

In [2]:
# 상기 역행렬 확인
print(np.dot(E1,e1))
print(np.dot(E2,e2))
print(np.dot(E3,e3))
print(np.dot(E4,e4))
print(np.dot(E5,e5))
print(np.dot(E6,e6))

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


---

$E_1$ 부터 $E_6$ 까지 차례대로 곱하면 identity matrix가 된다.

$E_6E_5E_4E_3E_2E_1A=I$

In [20]:
A1=np.dot(E1,A)
print(A)
print(A1)
print(E2)

[[ 0  1  2]
 [ 1  0  3]
 [ 4 -3  8]]
[[ 1  0  3]
 [ 0  1  2]
 [ 4 -3  8]]
[[ 1  0  0]
 [ 0  1  0]
 [-4  0  1]]


In [26]:
A2=np.dot(E2,A1)
print(E2)
print(A2)

[[ 1  0  0]
 [ 0  1  0]
 [-4  0  1]]
[[ 1  0  3]
 [ 0  1  2]
 [ 0 -3 -4]]


In [27]:
A3=np.dot(E3,A2)
print(E3)
print(A3)

[[1 0 0]
 [0 1 0]
 [0 3 1]]
[[1 0 3]
 [0 1 2]
 [0 0 2]]


In [28]:
A4=np.dot(E4,A3)
print(E4)
print(A4)

[[1.  0.  0. ]
 [0.  1.  0. ]
 [0.  0.  0.5]]
[[1. 0. 3.]
 [0. 1. 2.]
 [0. 0. 1.]]


In [29]:
A5=np.dot(E5,A4)
print(E5)
print(A5)

[[ 1  0  0]
 [ 0  1 -2]
 [ 0  0  1]]
[[1. 0. 3.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
A6=np.dot(E6,A5)
print(E6)
print(A6)

[[ 1  0 -3]
 [ 0  1  0]
 [ 0  0  1]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


---
반대로 identity matrix에 역행렬을 꺼꾸로 곱해 나가면 A 행렬이 된다.

$e_6E_6E_5E_4E_3E_2E_1A=e_6I \rightarrow E_5E_4E_3E_2E_1A=e_6I$<br>
$e_5E_5E_4E_3E_2E_1A=e_5e_6I \rightarrow E_4E_3E_2E_1A=e_5e_6I$<br>
$e_4E_4E_3E_2E_1A=e_4e_5e_6I \rightarrow E_3E_2E_1A=e_4e_5e_6I$<br>
$e_3E_3E_2E_1A=e_3e_4e_5e_6I \rightarrow E_2E_1A=e_3e_4e_5e_6I$<br>
$e_2E_2E_1A=e_2e_3e_4e_5e_6I \rightarrow E_1A=e_2e_3e_4e_5e_6I$<br>
$e_1E_1A=e_1e_2e_3e_4e_5e_6I \rightarrow A=e_1e_2e_3e_4e_5e_6I$<br>

행렬을 identity matrix에 기본행연산을 여러번 적용해서 만들 수 있다. (determinant가 0이 아닌 행렬)<br>
$A=E_pE_{p-1} ... E_1 I$<br>
$B=E_qE_{q-1} ... E_1 I$<br>
$det(AB)=det(E_pE_{p-1} ... E_1 IB)=det(E_pE_{p-1} ... E_1B)$<br>

- 기본행연산과의 곱의 determinant는 각각의 determinant의 곱과 같다.

$det(AB)=det(E_p)det(E_{p-1} ... E_1 IB)$ <br>
$det(AB)=det(E_p)det(E_{p-1})det(E_{p-2} ... E_1 IB)$ <br>
$\cdot$<br>
$\cdot$<br>
$\cdot$<br>
$det(AB)=det(E_p)det(E_{p-1})...det(E_1)det(B)$

- A 부분을 다시 합친다.

$det(AB)=det(E_pE_{p-1})...det(E_1)det(B)$ <br>
$det(AB)=det(E_pE_{p-1}...E_1)det(B)$<br>
$\cdot$<br>
$\cdot$<br>
$\cdot$<br>
$det(AB)=det(A)det(B)$