In [4]:
import numpy as np
%matplotlib qt
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from sympy import *

## 과제 1. 다음 세 개의 벡터가 일차 독립인지 확인하고, 일차 종속이면 한 벡터를 다른 두 벡터의 선형결합으로 표현하여라. 또한 quiver 를 이용하여 그림을 그려서 같은 평면상에 있는지 확인해라.

(a) a = [7,8,9], b = [1,2,3], c = [4,5,6]

In [5]:
A = np.array([[7,8,9], [1,2,3], [4,5,6]]).T
print(A)

[[7 1 4]
 [8 2 5]
 [9 3 6]]


In [6]:
Matrix(A).rref()

(Matrix([
 [1, 0, 1/2],
 [0, 1, 1/2],
 [0, 0,   0]]), (0, 1))

이를 보아 일차종속인 것을 볼 수 있다.

In [9]:
ax = plt.gca(projection='3d')
ML = np.max(A)
ax.set_xlim(0, ML)
ax.set_ylim(0, ML)
ax.set_zlim(0, ML)
ax.grid()
ax.quiver(np.zeros((3, 1)),np.zeros((3, 1)), np.zeros((3, 1)), A[:, 0], A[:, 1], A[:, 2])

(b) u = [1,0,2], v = [1,2,1], w = [-1,1,3]

In [12]:
B = np.array([[1,0,2], [1,2,1], [-1,1,3]]).T
print(B)

[[ 1  1 -1]
 [ 0  2  1]
 [ 2  1  3]]


In [13]:
Matrix(B).rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]), (0, 1, 2))

일차독립이다.

## 과제 2.

(1) 다음 벡터 x가 A의 영공간 N(A)의 원소인지 Python 으로 확인해라.

> A = np.array([[3,-5,-3], [6,-2,0], [-8,4,1]])

> x = np.array([[1], [3], [-4]])

In [32]:
#첫번째 방법
A = np.array([[3,-5,-3], [6,-2,0], [-8,4,1]])
Matrix(A).rref()

(Matrix([
 [1, 0, 1/4],
 [0, 1, 3/4],
 [0, 0,   0]]), (0, 1))

In [33]:
Matrix(A).nullspace()

[Matrix([
 [-1/4],
 [-3/4],
 [   1]])]

In [34]:
B = np.array(Matrix(A).nullspace())
for i in range(3):
    B[0, i] *= -4
print(B)

[[1 3 -4]]


In [37]:
#두번쨰 방법
x = np.array([[1], [3], [-4]])
np.dot(A, x)

array([[0],
       [0],
       [0]])

In [38]:
#두개 곱했을 때 0이므로 x 는 A의 N(A) 이다.

(2) 다음 행렬의 영공간을 강의 ppt 의 22page에서와 같이 구하시오. 자유변수는 s, t, u, v, w 순으로 쓰시오

> A = np.array([[1,4,5,2],[2,1,3,0],[-1,3,2,2]])

> B = np.array([[1,-2,0,4,0],[0,0,-1,-9,0],[0,0,0,0,-3]])

In [39]:
#(A)
A = np.array([[1,4,5,2],[2,1,3,0],[-1,3,2,2]])
Matrix(A).rref()

(Matrix([
 [1, 0, 1, -2/7],
 [0, 1, 1,  4/7],
 [0, 0, 0,    0]]), (0, 1))

x3 = s
x4 = t
x2 = -s - 4/7t
x1 = -s + 2/7t

그러므로 x = s*[-1, -1, 1, 0] + t*[2/7, -4/7, 0, 1] 이다.

(3) (2) 문제를 “2. 기본 지식과 자료”를 참조하여 Python으로 구하고 위의 풀이와 비교하라!

In [44]:
Matrix(A).nullspace()
#다음과 같이 나오므로 풀이가 같다.

[Matrix([
 [-1],
 [-1],
 [ 1],
 [ 0]]), Matrix([
 [ 2/7],
 [-4/7],
 [   0],
 [   1]])]

In [41]:
#(B)
B = np.array([[1,-2,0,4,0],[0,0,-1,-9,0],[0,0,0,0,-3]])
Matrix(B).rref()

(Matrix([
 [1, -2, 0, 4, 0],
 [0,  0, 1, 9, 0],
 [0,  0, 0, 0, 1]]), (0, 2, 4))

x2 = s, x4 = t //
x1 = 2s + -4t //
x3 = -9t //
x5 = 0

그러므로 x = s*[2, 1, 0, 0, 0] + t*[-4, 0, -9, 1, 0] 이다.

(3) (2) 문제를 “2. 기본 지식과 자료”를 참조하여 Python으로 구하고 위의 풀이와 비교하라!

In [43]:
Matrix(B).nullspace()
#다음과 같이 나오므로 풀이가 같다.

[Matrix([
 [2],
 [1],
 [0],
 [0],
 [0]]), Matrix([
 [-4],
 [ 0],
 [-9],
 [ 1],
 [ 0]])]

(4) 다음 벡터들로 생성된 공간의 차원 rref를 이용하여 구하고, Matrix(A).rank()함수를 이용하여 구한 것 과 같은지 확인하여라.
> (2, 7, 6) (0, 6, 8) (2, -5, -10) (3, 0, -5)

> (1, 2, 5, 10) (3, 1, 2, 5) (-2, 1, 3, 5) (4, 3, 7, 15) (5, 1, 3, 7)

In [66]:
# (2, 7, 6) (0, 6, 8) (2, -5, -10) (3, 0, -5) 일때,
A = np.array([[2, 7, 6], [0, 6, 8], [2, -5, -10], [3, 0, -5]]).T
Matrix(A).rref()

(Matrix([
 [1, 0,  1,  3/2],
 [0, 1, -2, -7/4],
 [0, 0,  0,    0]]), (0, 1))

In [67]:
#선행성분(0, 1)의 개수가 2
Matrix(A).rank()

2

In [68]:
# (1, 2, 5, 10) (3, 1, 2, 5) (-2, 1, 3, 5) (4, 3, 7, 15) (5, 1, 3, 7)
A = np.array([[1, 2, 5, 10], [3, 1, 2, 5], [-2, 1, 3, 5], [4, 3, 7, 15], [5, 1, 3, 7]]).T
Matrix(A).rref()

(Matrix([
 [1, 0,  1, 1, 0],
 [0, 1, -1, 1, 0],
 [0, 0,  0, 0, 1],
 [0, 0,  0, 0, 0]]), (0, 1, 4))

In [69]:
#선행성분(0, 1, 4)의 개수가 3
Matrix(A).rank()

3

(5) 다음 중 span{(1, 0, 2, 3), (-1, 2, 5, 3), ( -1, 1, 0, 2)} 에 속하는 것은 ?
> a = (-5, 6, 11, 3)

> b = (5, 2, 4, -7)

In [81]:
A = np.array([[1, 0, 2, 3], [-1, 2, 5, 3], [-1, 1, 0, 2]]).T
a = np.array([-5, 6, 11, 3])
b = np.array([5, 2, 4, -7])
aug = np.column_stack((A, a))
print(aug)

[[ 1 -1 -1 -5]
 [ 0  2  1  6]
 [ 2  5  0 11]
 [ 3  3  2  3]]


In [82]:
Matrix(aug).rref()

(Matrix([
 [1, 0, 0, -2],
 [0, 1, 0,  3],
 [0, 0, 1,  0],
 [0, 0, 0,  0]]), (0, 1, 2))

In [83]:
Matrix(aug).rank()

3

In [84]:
#차원의 개수가 3개 뿐이므로 a는 속하지 않는다.

In [85]:
AUG = np.column_stack((A, b))
print(AUG)

[[ 1 -1 -1  5]
 [ 0  2  1  2]
 [ 2  5  0  4]
 [ 3  3  2 -7]]


In [86]:
Matrix(AUG).rref()

(Matrix([
 [1, 0, 0, 0],
 [0, 1, 0, 0],
 [0, 0, 1, 0],
 [0, 0, 0, 1]]), (0, 1, 2, 3))

In [87]:
Matrix(AUG).rank()

4

In [88]:
#차원의 개수가 선행 성분의 갯수와 같으므로 b 는 A에 속한다

(6)다음 벡터들로 생성되는 공간의 기저를 구하시오
>  (1, 0, -3, -2) (0, 1,2, -3) (-3, -4, 1, 6) (1, -3, -8, 7) (2, 1, -6, 9)

In [93]:
A = np.array([[1, 0, -3, -2], [0, 1, 2, -3], [-3, -4, 1, 6], [1, -3, -8, 7], [2, 1, -6, 9]])
print(A)

[[ 1  0 -3 -2]
 [ 0  1  2 -3]
 [-3 -4  1  6]
 [ 1 -3 -8  7]
 [ 2  1 -6  9]]


In [94]:
Matrix(A).rref()

(Matrix([
 [1, 0, 0, 0],
 [0, 1, 0, 0],
 [0, 0, 1, 0],
 [0, 0, 0, 1],
 [0, 0, 0, 0]]), (0, 1, 2, 3))

In [97]:
#전부 일차 독립이므로 이런 벡터를 포함하는 기저가 존재한다.
#기저는 v = ([1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]) 이다.